<a href="https://colab.research.google.com/github/nandani2023-27/nandani/blob/main/notebooks/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Laboratory

![PyTorch](https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/PyTorch_logo_black.svg/960px-PyTorch_logo_black.svg.png)

Laboratory Lecture for the **Generative and Deep Learning** course — Master's Degree in Computer Science (2025–2026)

Riccardo Massidda — riccardo.massidda@di.unipi.it

In [ ]:
import torch

print(f"Using torch v{torch.__version__}")

Using torch v2.10.0+cpu


---
## Tensor Initialization

Tensors are the main data structure: multidimensional arrays with support for GPU acceleration, automatic differentiation, and NumPy-like indexing/broadcasting.

Key attributes:
- `dtype`: element type (`float32`, `float64`, `bfloat16`, `int64`, `uint8`, …)
- `device`: memory location (`cpu`, `cuda`, `mps`)
- `layout`: dense (`strided`) or sparse (`sparse_coo`)

In [ ]:
# Initialize a dense tensor of zeros
dims = (4, 5, 3)
t = torch.zeros(*dims)
print(f"Shape:  {t.shape}")
print(f"Type:   {t.dtype}")
print(f"Layout: {t.layout}")
print(t)

Shape:  torch.Size([4, 5, 3])
Type:   torch.float32
Layout: torch.strided
tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])


In [ ]:
# Initialize a sparse tensor of zeros
t_sparse = torch.zeros(*dims, layout=torch.sparse_coo)
print(f"Shape:  {t_sparse.shape}")
print(f"Type:   {t_sparse.dtype}")
print(f"Layout: {t_sparse.layout}")
print(t_sparse)

Shape:  torch.Size([4, 5, 3])
Type:   torch.float32
Layout: torch.sparse_coo
tensor(indices=tensor([], size=(3, 0)),
       values=tensor([], size=(0,)),
       size=(4, 5, 3), nnz=0, layout=torch.sparse_coo)


In [ ]:
# Define the indices for the non-zero elements
indices = torch.tensor([[0, 1],
                        [2, 2],
                        [3, 5]])

# Define the corresponding values
values = torch.tensor([2.5, -1.5])

new_t_sparse = torch.sparse_coo_tensor(indices, values, dims)

print(f"Shape:  {new_t_sparse.shape}")
print(f"Type:   {new_t_sparse.dtype}")
print(f"Layout: {new_t_sparse.layout}")
print(new_t_sparse)

# You can convert it to a dense tensor to see the values clearly
print("\nDense representation:\n", new_t_sparse.to_dense())

Shape:  torch.Size([4, 5, 3])
Type:   torch.float32
Layout: torch.sparse_coo
tensor(indices=tensor([[0, 1],
                       [2, 2],
                       [3, 5]]),
       values=tensor([ 2.5000, -1.5000]),
       size=(4, 5, 3), nnz=2, layout=torch.sparse_coo)

Dense representation:
 tensor([[[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 2.5000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000, -1.5000],
         [ 0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000]],

        [[ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000,  0.0000,  0.0000],
         [ 0.0000

In [ ]:
# Random tensors
t1 = torch.randn(*dims)             # Standard normal
t2 = torch.rand(*dims)              # Uniform [0, 1)
t3 = torch.randint(-10, 10, dims)   # Uniform integers

print(f"t1 dtype: {t1.dtype}")  # float32
print(f"t2 dtype: {t2.dtype}")  # float32
print(f"t3 dtype: {t3.dtype}")  # int64

print("t1:\n", t1)
print("t2:\n", t2)
print("t3:\n", t3)

t1 dtype: torch.float32
t2 dtype: torch.float32
t3 dtype: torch.int64
t1:
 tensor([[[ 1.1329e+00,  4.9254e-02,  6.0836e-01],
         [-6.8955e-01,  1.1295e+00, -7.4990e-01],
         [ 4.4000e-02, -2.1077e+00, -1.1137e-03],
         [-1.5777e-02,  1.6527e+00,  1.1884e+00],
         [-5.8477e-01,  4.4809e-01, -1.1586e-01]],

        [[ 2.0463e+00, -8.6014e-01, -1.4789e+00],
         [-8.7991e-01, -1.3264e+00,  2.2877e-01],
         [ 2.6298e-01, -2.9991e-01,  1.6626e+00],
         [-2.1826e+00,  2.0216e-02,  8.8218e-01],
         [ 3.4145e-01,  3.2941e-01, -1.4416e+00]],

        [[ 8.8595e-01, -2.2682e-01, -6.0788e-01],
         [ 1.8096e-01, -9.2093e-01, -1.1561e+00],
         [-1.5566e+00, -3.9812e-01,  8.9890e-01],
         [-1.6991e+00,  7.5369e-01,  6.1137e-01],
         [-1.2501e+00,  2.7264e-01, -1.7430e-01]],

        [[-1.9997e+00,  1.0510e+00, -1.5558e-01],
         [-4.1098e-02, -5.6218e-01,  1.6034e+00],
         [ 5.1727e-01,  2.0769e+00,  8.3993e-01],
         [-1.0797e+

In [ ]:
import numpy as np

# Other initialization methods
print(torch.ones(2, 3))
print(torch.linspace(0, 1, steps=5))

arr = np.array([1, 2, 3])
print(torch.from_numpy(arr))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
tensor([1, 2, 3])


In [ ]:
# Types are promoted automatically by operators
t4 = t1 + t2 * t3
print(f"t4 dtype: {t4.dtype}")  # float32 (int64 promoted)

t4 dtype: torch.float32


In [ ]:
# Manual type casting
torch.manual_seed(42)
dims = (3, 2)
t5 = torch.randint(0, 2, dims)
print(f"Original ({t5.dtype}):\n{t5}")
print(f"Bool     ({t5.bool().dtype}):\n{t5.bool()}")
print(f"Float32  ({t5.float().dtype}):\n{t5.float()}")
print(f"Int64    ({t5.long().dtype}):\n{t5.long()}")
print(f"Float64  ({t5.double().dtype}):\n{t5.double()}")

Original (torch.int64):
tensor([[0, 1],
        [0, 0],
        [0, 1]])
Bool     (torch.bool):
tensor([[False,  True],
        [False, False],
        [False,  True]])
Float32  (torch.float32):
tensor([[0., 1.],
        [0., 0.],
        [0., 1.]])
Int64    (torch.int64):
tensor([[0, 1],
        [0, 0],
        [0, 1]])
Float64  (torch.float64):
tensor([[0., 1.],
        [0., 0.],
        [0., 1.]], dtype=torch.float64)


---
## Tensor Operations

Some operators are overloaded:
- `+`, `-` for addition and subtraction (support broadcasting)
- `*` is **elementwise** multiplication (not matrix product, supports broadcasting)
- `@` for matrix multiplication (`torch.matmul`)

In-place operations use a trailing underscore: `add_`, `sub_`, etc.

In [ ]:
a = torch.tensor([[1., 2.], [3., 4.]])
b = torch.tensor([[10., 20.], [30., 40.]])

print("a + b =\n", a + b)            # elementwise addition
print("a * b =\n", a * b)            # elementwise multiplication
print("a @ b =\n", a @ b)            # matrix multiplication
print("torch.matmul(a, b) =\n", torch.matmul(a, b))  # same as @

a + b =
 tensor([[11., 22.],
        [33., 44.]])
a * b =
 tensor([[ 10.,  40.],
        [ 90., 160.]])
a @ b =
 tensor([[ 70., 100.],
        [150., 220.]])
torch.matmul(a, b) =
 tensor([[ 70., 100.],
        [150., 220.]])


In [ ]:
# In-place operations modify the tensor directly
c = torch.zeros(2, 2)
print(f"Before: {c}")
c.add_(a)
print(f"After add_(a): {c}")

Before: tensor([[0., 0.],
        [0., 0.]])
After add_(a): tensor([[1., 2.],
        [3., 4.]])


---
## Broadcasting Rules

PyTorch broadcasting follows NumPy semantics.
Two tensors are "broadcastable" if:
1. Each tensor has at least one dimension.
2. Iterating from the **trailing** dimension, sizes must be equal, one of them is 1, or one of them does not exist.

In [ ]:
# Same shapes: always broadcastable
x = torch.empty(5, 7, 3)
y = torch.empty(5, 7, 3)
print(f"(5,7,3) + (5,7,3) → {(x + y).shape}")

# Trailing dimensions: equal, or one is 1, or missing
x = torch.empty(5, 3, 4, 1)
y = torch.empty(   3, 1, 1)
print(f"(5,3,4,1) + (3,1,1) → {(x + y).shape}")  # → (5,3,4,1)

# Trailing dimensions: equal, or one is 1, or missing
x = torch.empty(2, 5, 3, 4, 1)
y = torch.empty(      3, 1, 1)
print(f"(2,5,3,4,1) + (3,1,1) → {(x + y).shape}")  # → (2,5,3,4,1)

(5,7,3) + (5,7,3) → torch.Size([5, 7, 3])
(5,3,4,1) + (3,1,1) → torch.Size([5, 3, 4, 1])
(2,5,3,4,1) + (3,1,1) → torch.Size([2, 5, 3, 4, 1])


In [ ]:
# Not broadcastable: trailing dimension 2 != 3
x = torch.empty(5, 2, 4, 1)
y = torch.empty(   3, 1, 1)
try:
    z = x + y
except RuntimeError as e:
    print(f"Error: {e}")

Error: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1


In [ ]:
# Concrete example: row vector + column vector
row = torch.tensor([1, 2, 3])           # shape (3,)
col = torch.tensor([[0], [10], [20], [30]])  # shape (4, 1)
result = row + col                       # shape (4, 3)
print(f"row {row.shape} + col {col.shape} → {result.shape}")
print(result)

row torch.Size([3]) + col torch.Size([4, 1]) → torch.Size([4, 3])
tensor([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [ ]:
# Scalar broadcasting: a scalar can be broadcast to any shape
x = torch.tensor([1, 2, 3])  # Shape (3,)
s = torch.tensor(10)        # Shape ()
result = x + s
print(f"x {x.shape} + s {s.shape} → {result.shape}")
print(f"Result:\n{result}")

x torch.Size([3]) + s torch.Size([]) → torch.Size([3])
Result:
tensor([11, 12, 13])


In [ ]:
# Broadcasting with a 1-sized dimension
a = torch.arange(12).reshape(3, 4) # Shape (3, 4)
b = torch.arange(4)              # Shape (4,)
result = a + b
print(f"a {a.shape} + b {b.shape} → {result.shape}")
print(f"Result:\n{result}")

a torch.Size([3, 4]) + b torch.Size([4]) → torch.Size([3, 4])
Result:
tensor([[ 0,  2,  4,  6],
        [ 4,  6,  8, 10],
        [ 8, 10, 12, 14]])


In [ ]:
# Another example with 1-sized dimension
c = torch.arange(3).reshape(3, 1) # Shape (3, 1)
d = torch.arange(4).reshape(1, 4) # Shape (1, 4)
result = c + d
print(f"c {c.shape} + d {d.shape} → {result.shape}")
print(f"Result:\n{result}")

c torch.Size([3, 1]) + d torch.Size([1, 4]) → torch.Size([3, 4])
Result:
tensor([[0, 1, 2, 3],
        [1, 2, 3, 4],
        [2, 3, 4, 5]])


In [ ]:
# Broadcasting with different number of dimensions
e = torch.arange(6).reshape(2, 3)    # Shape (2, 3)
f = torch.tensor([10, 20, 30])       # Shape (3,)
result = e * f
print(f"e {e.shape} * f {f.shape} → {result.shape}")
print(f"Result:\n{result}")

e torch.Size([2, 3]) * f torch.Size([3]) → torch.Size([2, 3])
Result:
tensor([[  0,  20,  60],
        [ 30,  80, 150]])


---
## Device Management (GPU / MPS / CPU)

The submodule `torch.cuda` provides the API for NVIDIA GPU management.
On Apple Silicon, the MPS (Metal Performance Shaders) backend is available.

All tensors in an operation must reside on the **same device**.

In [ ]:
# Device-agnostic pattern
device = (
    "cuda" if torch.cuda.is_available()
    else "mps" if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using device: {device}")

Using device: cpu


In [ ]:
# Move tensors to the accelerator
t1_dev = t1.to(device)
t2_dev = t2.to(device)
t3_dev = t3.to(device)

# Operations on the same device
t4_dev = t1_dev + t2_dev * t3_dev
print(f"Result device: {t4_dev.device}")

Result device: cpu


In [ ]:
# Mixing devices raises a RuntimeError
if device != "cpu":
    try:
        bad = t4_dev + t4  # t4 is on CPU, t4_dev is on the accelerator
    except RuntimeError as e:
        print(f"Expected error: {e}")
else:
    print("Skipped (no accelerator — both tensors are on CPU)")

Skipped (no accelerator — both tensors are on CPU)


---
## Tensor Indexing

Basic indexing works like Python lists, extended to multiple dimensions.
Boolean arrays can filter elements satisfying a condition.
If fewer indices than dimensions are given, the missing indices are treated as full slices.

In [ ]:
torch.manual_seed(42)
arr = torch.arange(24).reshape(3, 4, 2)
print(f"Shape: {arr.shape}")
arr

In [ ]:
# First two entries along dim 0
arr[:2]

In [ ]:
# Last two entries along dim 0
arr[1:]

In [ ]:
# Negative indexing
arr[-2:]

In [ ]:
# Mixed indexing
arr[1:, 1:3]

In [ ]:
arr[-2:, 1:3, :]

In [ ]:
# Boolean indexing
even_entries = arr % 2 == 0
print(even_entries)
arr_copy = arr.clone()
arr_copy[even_entries] = -1
arr_copy

---
## Tensor Reshaping

In [ ]:
t = torch.randn(3, 1, 5)
t

tensor([[[ 1.1561,  0.3965, -2.4661,  0.3623,  0.3765]],

        [[-0.1808,  0.3930,  0.4327, -1.3627,  1.3564]],

        [[ 0.6688, -0.7077, -0.3267, -0.2788, -0.4220]]])

In [ ]:
t.squeeze().shape     # remove singleton dims → [3, 5]

torch.Size([3, 5])

In [ ]:
t.unsqueeze(0).shape  # add dim at 0 → [1, 3, 1, 5]

torch.Size([1, 3, 1, 5])

In [ ]:
t.unsqueeze(3).shape  # add dim at 3 → [3, 1, 5, 1]

torch.Size([3, 1, 5, 1])

In [ ]:
t.transpose(1, 2).shape  # swap dims 1,2 → [3, 5, 1]

torch.Size([3, 5, 1])

In [ ]:
t.permute(1, 0, 2).shape  # reorder → [1, 3, 5]

torch.Size([1, 3, 5])

### `view` vs `reshape`

- `view` requires the tensor to be **contiguous** in memory (raises error otherwise).
- `reshape` works on any tensor (may silently copy data).

⚠ Use `reshape` unless you specifically want the error as a safety check.

In [ ]:
x = torch.randn(3, 4)

# OK: x is contiguous
x.view(12)
x.view(2, 6)

# transpose makes it non-contiguous
y = x.t()
print(f"y is contiguous: {y.is_contiguous()}")

try:
    y.view(12)                 # RuntimeError!
except RuntimeError as e:
    print(f"view error: {e}")

print(y.reshape(12).shape)            # OK (silently copies)
print(y.contiguous().view(12).shape)  # OK (explicit copy)

y is contiguous: False
view error: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
torch.Size([12])
torch.Size([12])


---
## Tensor Reduction

Reduction operations collapse the tensor dimensionality: `sum`, `mean`, `prod`, `amin`, `amax`.

The `keepdim` parameter preserves a singleton dimension in place.

In [ ]:
t = torch.randn(5, 2, 3)

In [ ]:
red_t = t.sum(0)
print(f"Shape: {red_t.shape}")
red_t

In [ ]:
red_t = t.sum(0, keepdim=True)
print(f"Shape: {red_t.shape}")
red_t

In [ ]:
red_t = t.mean(0)
print(f"Shape: {red_t.shape}")
red_t

In [ ]:
red_t = t.mean((0, 2), keepdim=True)
print(f"Shape: {red_t.shape}")
red_t

---
## Your Turn! — Kaiming Initialization

The Kaiming uniform initialization scheme provides a standard baseline to train Neural Networks with rectified activation functions.

$$w \sim \mathcal{U}\left(-\sqrt{\frac{6}{\text{fan\_in}}},\ \sqrt{\frac{6}{\text{fan\_in}}}\right)$$

Write the following functions:
- `relu_kaiming_init_(weights)` — modifies the tensor **in-place**
- `relu_kaiming_init(in_size, out_size)` — returns a new `(out_size, in_size)` tensor

In [ ]:
def relu_kaiming_init(in_size: int, out_size: int) -> torch.Tensor:
    t = tourch.empty(out_size , in_size)
    bound = (6.0 / in_size) ** 0.5
    #torch.nn.init.uniform_(t, -bound, bound)
    t =
    pass


def relu_kaiming_init_(weights: torch.Tensor):
    # TODO: your code here
    pass

In [ ]:
# --- Tests (do not modify) ---
torch.manual_seed(42)

# Shape check
t1 = relu_kaiming_init(5, 10)
assert t1.shape == (10, 5), f"Expected (10, 5), got {t1.shape}"

# In-place check
t2 = torch.zeros(30, 25)
t2_old = t2.clone()
relu_kaiming_init_(t2)
assert not torch.allclose(t2_old, t2), "In-place init did not modify the tensor"
assert torch.allclose(t2_old, torch.tensor(0.0))

# Stats
print(f"Mean: {t2.mean():.4f}")
print(f"Std:  {t2.std():.4f}")
print("All tests passed!")

---
## Autograd — Automatic Differentiation

The `torch.autograd` engine builds a **dynamic computation graph** during the forward pass. Each operation creates a `Function` node connected to its `Tensor` arguments. Calling `.backward()` traverses this graph in reverse to compute gradients.

Key tensor attributes:
- `.data` — the raw data
- `.grad` — accumulated gradient (initially `None`)
- `.grad_fn` — the `Function` that created this tensor

In [ ]:
t = torch.randn(2, 4, 5)
t.data, t.grad, t.grad_fn

(tensor([[[-0.1177, -0.2986,  1.5193,  0.0358,  1.0366],
          [ 0.8817, -1.3237, -0.3675,  0.0585, -1.6682],
          [-0.0200, -1.2131,  1.1971, -0.7818,  1.1162],
          [ 0.2916,  0.2794, -0.5718,  1.9491, -0.4252]],
 
         [[-0.3753,  1.4467, -0.7872,  2.4992, -0.7532],
          [-0.0555,  0.3220,  0.4461,  1.5230,  1.2805],
          [-0.1162,  1.3705,  0.1967, -0.4063, -1.3642],
          [ 0.0082, -0.4059, -0.7111, -0.3496,  0.3797]]]),
 None,
 None)

In [ ]:
# A simple RNN step — autograd tracks everything
torch.manual_seed(42)
batch_size, in_shape, hh_shape = 32, 5, 10

# Input and hidden state (no grad needed)
x = torch.randn(batch_size, in_shape)
prev_h = torch.randn(batch_size, hh_shape)

# Parameters — we want their gradients
W_x = torch.randn(hh_shape, in_shape, requires_grad=True)
W_h = torch.randn(hh_shape, hh_shape, requires_grad=True)

# Forward: next_h = tanh(x @ W_x^T + prev_h @ W_h^T)
i2h = torch.mm(x, W_x.t())
h2h = torch.mm(prev_h, W_h.t())
next_h = (i2h + h2h).tanh()

print(f"next_h shape: {next_h.shape}")
print(f"next_h.grad_fn: {next_h.grad_fn}")

next_h shape: torch.Size([32, 10])
next_h.grad_fn: <TanhBackward0 object at 0x7fa8a005ffd0>


In [ ]:
# Backward: compute gradients
# For non-scalar output, pass a gradient tensor of matching shape
next_h.backward(torch.ones(batch_size, hh_shape))

# Only tensors with requires_grad=True accumulate gradients
print(f"x.grad:      {x.grad}")       # None
print(f"prev_h.grad: {prev_h.grad}")  # None
print(f"W_x.grad shape: {W_x.grad.shape}")
print(f"W_h.grad shape: {W_h.grad.shape}")

x.grad:      None
prev_h.grad: None
W_x.grad shape: torch.Size([10, 5])
W_h.grad shape: torch.Size([10, 10])


### `requires_grad`, `detach()`, `no_grad()`, `inference_mode()`

- `requires_grad=True`: autograd tracks this tensor. Use for model parameters.
- `requires_grad=False`: no tracking. Use for input data or constants.
- `.detach()`: returns a new tensor sharing data but **outside** the graph.
- `torch.no_grad()`: context manager disabling gradient tracking for a block.
- `torch.inference_mode()`: stricter and faster than `no_grad()` (PyTorch 1.9+). Preferred at inference time.

⚠ In-place modification of a leaf tensor with `requires_grad=True` raises an error.

In [ ]:
# detach()
x = torch.randn(3, requires_grad=True)
y = x ** 2
z = y.detach()   # shares data, but no gradient flows through z

print(f"z.requires_grad: {z.requires_grad}")      # False
print(f"Same memory: {z.data_ptr() == y.data_ptr()}")  # True

z.requires_grad: False
Same memory: True


In [ ]:
# no_grad()
w = torch.randn(3, requires_grad=True)

# In-place on leaf tensor → error
try:
    w.add_(1)
except RuntimeError as e:
    print(f"Expected: {e}")

# Inside no_grad() it's fine
with torch.no_grad():
    w.add_(1)
    print(f"w after in-place add: {w}")

Expected: a leaf Variable that requires grad is being used in an in-place operation.
w after in-place add: tensor([ 1.4016,  1.2595, -0.2378], requires_grad=True)


In [ ]:
# inference_mode() — stricter than no_grad()
with torch.no_grad():
    y = torch.randn(1)
y.requires_grad = True   # OK after no_grad
z = y + 1
print(f"z.grad_fn: {z.grad_fn}")  # AddBackward0

with torch.inference_mode():
    x = torch.randn(1)
    y = x + 1

try:
    y.requires_grad = True   # RuntimeError!
except RuntimeError as e:
    print(f"inference_mode error: {e}")

z.grad_fn: <AddBackward0 object at 0x7fa89e169f90>
inference_mode error: Setting requires_grad=True on inference tensor outside InferenceMode is not allowed.


---
## Your Turn! — Linear Regression with Raw Autograd

Implement a linear regression training loop using **only tensors and autograd** — no `nn.Module`, no optimizer.

The true model is $y = 3x + 2 + \varepsilon$.

What's `torch.manual_seed(42)`?

In [ ]:
torch.manual_seed(42)
X = torch.randn(100, 1)
y = 3 * X + 2 + 0.1 * torch.randn(100, 1)

# TODO: initialize w, b with requires_grad=True
w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

lr = 0.1

for epoch in range(20):
    # TODO: forward pass, loss, backward, update, zero grads
    y_pred = X @ w + b
    #loss
    loss = ((y_pred - y) ** 2).mean()

    #backword
    loss.backward()

   # update
    with torch.no_grad():
        w -= lr * w.grad
        b -= lr * b.grad
    # zero grads
    w.grad.zero_()
    b.grad.zero_()

    if epoch % 2:
      print(epoch , loss.item(), w.item(), b.item())

1 12.416971206665039 0.30191999673843384 0.6405047178268433
3 10.242551803588867 0.22611719369888306 1.1897609233856201
5 9.336984634399414 0.1662350445985794 1.5428191423416138
7 8.958407402038574 0.12048222869634628 1.7699768543243408
9 8.799543380737305 0.08634293079376221 1.9162689447402954
11 8.732630729675293 0.061314914375543594 2.0105724334716797
13 8.704344749450684 0.04321512579917908 2.071420669555664
15 8.69234561920166 0.03026685304939747 2.110719919204712
17 8.687238693237305 0.021085135638713837 2.1361258029937744
19 8.685056686401367 0.01462157629430294 2.1525654792785645


---
## Building Models with `torch.nn`

`torch.nn` contains the basic components to define neural networks, loss functions, regularization techniques, and optimizers.

**`nn.Module`** is the base class for all components: `Linear`, `Conv2d`, `RNN`, …

Each `Module` contains `Parameter` objects (tensors with `requires_grad=True`). The `parameters()` method returns an iterator over all of them.

Container classes:
- `nn.Sequential(*modules)`: chains modules in order; `forward` is implicit.
- `nn.ModuleList(modules)`: for custom forward logic (loops, conditionals, skip connections).

⚠ If you use a regular Python `list`, the parameters will **not** be registered!

### `torch.nn` vs `torch.nn.functional`

Apart from modules, PyTorch offers a **functional API** (`torch.nn.functional`) with stateless functions you can call directly in the `forward` method.

👍 Rule of thumb: use **modules** for layers with learnable parameters (`Linear`, `Conv2D`) or state (`BatchNorm`, `Dropout`). Use **functional** for pure activations and stateless operations inside `forward`.

In [ ]:
import torch.nn as nn
import torch.nn.functional as F

# A custom linear layer using our Kaiming init
class GDL_LinearLayer(nn.Module):
    def __init__(self, in_shape, out_shape, kaiming_custom=False):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(out_shape, in_shape))
        self.bias = nn.Parameter(torch.randn(out_shape))

        if kaiming_custom:
            # Why would this error without torch.no_grad()?
            with torch.no_grad():
                relu_kaiming_init_(self.weight)
        else:
            nn.init.kaiming_uniform_(self.weight, mode="fan_in", nonlinearity="relu")

        nn.init.zeros_(self.bias)

    def forward(self, in_tensor):
        return in_tensor @ self.weight.t() + self.bias

In [ ]:
# Multi-layer Perceptron: ModuleList vs plain list
class GDL_MultilayerPerceptron(nn.Module):
    def __init__(self, layer_sizes: list[int], use_module_list: bool = True):
        """
        MLP where layer_sizes = [input_dim, hidden1, ..., output_dim].
        Set use_module_list=False to see what goes wrong with a plain list.
        """
        super().__init__()

        layers = [
            GDL_LinearLayer(layer_sizes[i], layer_sizes[i + 1])
            for i in range(len(layer_sizes) - 1)
        ]

        if use_module_list:
            self.fc = nn.ModuleList(layers)
        else:
            # ⚠ BUG: parameters not registered!
            self.fc = layers

    def forward(self, x):
        for layer in self.fc:
            x = F.relu(layer(x))
        return x

In [ ]:
# Compare: ModuleList vs plain list
layers = [5, 10, 20, 1]

net_correct = GDL_MultilayerPerceptron(layers, use_module_list=True)
net_broken = GDL_MultilayerPerceptron(layers, use_module_list=False)

print(f"ModuleList → {len(list(net_correct.parameters()))} parameters registered")
print(f"Plain list → {len(list(net_broken.parameters()))} parameters registered ⚠")

ModuleList → 6 parameters registered
Plain list → 0 parameters registered ⚠


---
## Datasets and Data Loaders

The module `torch.utils.data` defines classes to handle datasets and load data.

`DataLoader` automatizes mini-batching, shuffling, sampling, pre-processing, and parallel loading.

In [ ]:
# Generate synthetic data from our correct net
torch.manual_seed(42)

n_samples = 1000
x_data = torch.randn(n_samples, 5)

with torch.no_grad():
    y_data = net_correct(x_data) + 1e-2 * torch.randn(n_samples, 1)

print(f"x_data: {x_data.shape}")
print(f"y_data: {y_data.shape}")

x_data: torch.Size([1000, 5])
y_data: torch.Size([1000, 1])


In [ ]:
# Create TensorDataset and split train / val / test
dataset = torch.utils.data.TensorDataset(x_data, y_data)

n_train = int(0.7 * n_samples)
n_val = int(0.2 * n_samples)
n_test = n_samples - n_train - n_val

train_set, val_set, test_set = torch.utils.data.random_split(
    dataset, [n_train, n_val, n_test])

batch_size = 32
train_loader = torch.utils.data.DataLoader(train_set, batch_size, shuffle=True)
val_loader = torch.utils.data.DataLoader(val_set, batch_size)
test_loader = torch.utils.data.DataLoader(test_set, batch_size)

print(f"Batches — train: {len(train_loader)}, val: {len(val_loader)}, test: {len(test_loader)}")

Batches — train: 22, val: 7, test: 4


### Training Loop

To define a training loop, we need a **loss function** and an **optimizer**.

Always check the documentation for correct shape and input arguments!

⚠ Remember to reset gradients with `zero_grad()` — they accumulate by default!

In [ ]:
# Training loop
net_hat = GDL_MultilayerPerceptron([5, 5, 5, 1])
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(net_hat.parameters(), lr=1e-2)

n_epochs = 500
tr_loss = []
vl_loss = []

for epoch in range(n_epochs):
    # Train
    net_hat.train()
    epoch_tr_loss = []
    for x, y in train_loader:
        optimizer.zero_grad()
        y_hat = net_hat(x)
        loss = loss_fn(y_hat, y)
        loss.backward()
        optimizer.step()
        epoch_tr_loss.append(loss.item())

    # Validation
    net_hat.eval()
    epoch_val_loss = []
    with torch.no_grad():
        for x, y in val_loader:
            y_hat = net_hat(x)
            loss = loss_fn(y_hat, y)
            epoch_val_loss.append(loss.item())

    avg_tr = sum(epoch_tr_loss) / len(epoch_tr_loss)
    avg_vl = sum(epoch_val_loss) / len(epoch_val_loss)
    tr_loss.append(avg_tr)
    vl_loss.append(avg_vl)

    if epoch % 50 == 0:
        print(f"Epoch {epoch:3d} | Train: {avg_tr:.4f} | Val: {avg_vl:.4f}")

Epoch   0 | Train: 1.1337 | Val: 0.7458
Epoch  50 | Train: 0.0846 | Val: 0.0654
Epoch 100 | Train: 0.0589 | Val: 0.0532
Epoch 150 | Train: 0.0481 | Val: 0.0450
Epoch 200 | Train: 0.0398 | Val: 0.0428
Epoch 250 | Train: 0.0367 | Val: 0.0430
Epoch 300 | Train: 0.0348 | Val: 0.0428
Epoch 350 | Train: 0.0338 | Val: 0.0432
Epoch 400 | Train: 0.0330 | Val: 0.0430
Epoch 450 | Train: 0.0324 | Val: 0.0425


In [ ]:
# Test set performance
net_hat.eval()
test_loss_values = []
with torch.no_grad():
    for x, y in test_loader:
        y_hat = net_hat(x)
        loss = loss_fn(y_hat, y)
        test_loss_values.append(loss.item())

test_loss = sum(test_loss_values) / len(test_loss_values)
print(f"Test Loss: {test_loss:.4f}")

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 4))
plt.plot(tr_loss, label="Train Loss")
plt.plot(vl_loss, label="Val Loss")
plt.axhline(y=test_loss, color='r', linestyle='--', label="Test Loss")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()
plt.title("Training Curves")
plt.tight_layout()
plt.show()

---
## Compilation

`torch.compile()` JIT-compiles the model's computation graph, fusing operations and reducing Python overhead. A single line can give a significant speedup.

```python
model = torch.compile(model)
```

The first call is slower (compilation), subsequent calls are faster. Works best on Linux + CUDA.

---
## Logging

Several metrics can help understand your model. Logging them is always a good idea!

**TensorBoard** works great for PyTorch. Otherwise, cloud-based tools like Weights & Biases, neptune.ai, etc.

---
## Model Serialization

The state dictionary stores the value of all model parameters.

In [ ]:
# Save
torch.save(net_hat.state_dict(), "model_weights.pt")

# Load
net_loaded = GDL_MultilayerPerceptron([5, 5, 5, 1])
net_loaded.load_state_dict(torch.load("model_weights.pt", weights_only=True))
net_loaded.eval()

# Verify
with torch.no_grad():
    sample = torch.randn(1, 5)
    assert torch.allclose(net_hat(sample), net_loaded(sample))
    print("Model loaded — predictions match!")

---
## PyTorch Ecosystem

Understanding how things work under-the-hood is worth the effort, but in practice most routine operations can be abstracted away.

Both **Lightning** and **Transformers** by HuggingFace provide APIs for training, logging, evaluating, and inference.

Also: graph neural networks, interpretability, continual learning, federated learning, quantum ML, …

---
## Your Turn! — MNIST CNN

Implement and train a **Convolutional Neural Network** to perform image classification on the MNIST dataset.

📜 Side Quests:
1. Monitor the performance with a logger
2. Play around with `dropout`, `batch_norm`, etc. (remember `train()` vs `eval()`!)
3. Try a Lightning implementation

In [ ]:
import torchvision
from torchvision import transforms
import torch
torch.manual_seed(42)

# Load MNIST
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,)),
])

mnist_train_full = torchvision.datasets.MNIST(
    'data/', train=True, download=True, transform=transform)
mnist_test = torchvision.datasets.MNIST(
    'data/', train=False, download=True, transform=transform)

# TODO: Split mnist_train_full into train and validation
n_val = 10000
n_train = len(mnist_train_full) - n_val
train_set, val_set = torch.utilss.data
# TODO: Create DataLoaders

# TODO: Select device

100%|██████████| 9.91M/9.91M [00:00<00:00, 39.7MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.08MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 9.96MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 12.9MB/s]


In [ ]:
# TODO: Define your CNN class

class CNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 8, kernel_size=3, padding=1)
        self.conv2 = nn.Conv2d(8, 16, kernel_size=3, padding=1)
        self.pool = nn.MaxPool2d(2)
        self.fc1 = nn.Linear(16 * 7 * 7, 32)
        self.fc2 = nn.Linear(32, 10)

        # TODO

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = X.view(X.size(0), 784)
        x = F.relu(self.fc1(x))
        x =
        # TODO
        pass

In [ ]:
# TODO: Instantiate CNN, loss function, optimizer

# TODO: Training loop

# TODO: Test set evaluation (accuracy!)

# TODO: Plot training and validation loss